<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GmToolkit.Core\GmToolkit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="sqlite-net-pcl" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
